### ISSUE TITLE
Can't sign in on Windows

### ISSUE THREAD

**Issue by Layerex** [3bl3gamer/tgclient#25]
[Code used to sign in](https://github.com/Layerex/telegram-export-gifs/blob/c9e0b22faf8941ce58f1ed0a47e2454a703cc6bc/client.go#L25)

Error:
```
panic: interface conversion: mtproto.TL is mtproto.TL_bad_msg_notification, not mtproto.VectorObject

goroutine 1 [running]:
main.(*Telegram).SignIn(0xc0000d2000, 0x43c5, {0xc4fb06, 0x20}, {0xc000036400, 0x3c})
        C:/Users/xd/Downloads/telegram-export-gifs-master/client.go:55 +0x326
main.main()
        C:/Users/xd/Downloads/telegram-export-gifs-master/main.go:102 +0xfe
```

No output, besides error.

On Linux, works perfectly.

**Comment by 3bl3gamer** [comment]
I've tried to run the gif exporter twice in a row and got these errors:

```
$ ./telegram-export-gifs.exe
Enter phone number: 123...
Enter code: panic: RPC: mtproto.TL_rpc_error{ErrorCode:400, ErrorMessage:"PHONE_CODE_INVALID"}

<stack>

$ ./telegram-export-gifs.exe
panic: interface conversion: mtproto.TL is mtproto.TL_bad_msg_notification, not mtproto.VectorObject

<stack>
```

Looks like the actual problem is in outdated `ScanfAuthDataProvider` which reads empty confirmation code and fails on Windows. This was fixed in [v0.143.1](https://github.com/3bl3gamer/tgclient/commit/29badd7eb5cb129b9c8209f5591f8b95aadf47f5) and your tool uses [v0.138.2](https://github.com/Layerex/telegram-export-gifs/blob/c9e0b22faf8941ce58f1ed0a47e2454a703cc6bc/go.mod#L6).

The `TL_bad_msg_notification` error is known but rare. It sometimes occurs after interrupted authorization, is platform independent and goes away after client reconnection.
